spring:
  application:
    name: Pokecarte

  datasource:
    url: jdbc:mysql://${DB_HOST_DEV}:${DB_PORT_DEV}/${DB_NAME_DEV}?createDatabaseIfNotExist=true
    username: ${DB_USER_DEV}
    password: ${DB_PASSWORD_DEV}

  profiles:
    active:
      - development

  config:
    import:
      - "configtree:./"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: never

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

logging:
  level:
    org:
      springframework:
        web: debug

cors:
  allowedOrigins: ${CLIENT_URL_DEV}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION_MS}
