INSERT INTO set_card (id, name, logo, release_date, created_at, updated_At)
VALUES
(
    "swsh3",
    "Ténèbres Embrasées",
    "https://assets.tcgdex.net/fr/swsh/swsh3/logo.webp",
    "2020-08-14",
    NOW(),
    NOW()
),
(
    "swsh1",
    "Épée et Bouclier",
    "https://assets.tcgdex.net/fr/swsh/swsh1/logo.webp",
    "2020-02-07",
    NOW(),
    NOW()
),
(
    "swsh4.5",
    "Destinées Radieuses",
    "https://assets.tcgdex.net/fr/swsh/swsh4.5/logo.webp",
    "2021-02-19",
    NOW(),
    NOW()
);

INSERT INTO product (id, name, image, category, illustrator, rarity, hp, evolve_from, description, stage, retreat, price, stock, discount, set_id, created_at, updated_At)
VALUES
(
    "swsh3-136",
    "Fouinar",
    "https://assets.tcgdex.net/fr/swsh/swsh3/136/high.webp",
    "Pokemon",
    "tetsuya koizumi",
    "Peu Commune",
    110,
    "Fouinette",
    null,
    "Niveau 1",
    1,
    0.11,
    50,
    0,
    "swsh3",
    NOW(),
    NOW()
),
(
    "swsh1-1",
    "Celebi V",
    "https://assets.tcgdex.net/fr/swsh/swsh1/1/high.webp",
    "Pokemon",
    "PLANETA Igarashi",
    "Holo Rare V",
    180,
    null,
    null,
    "De base",
    1,
    2.27,
    37,
    0,
    "swsh1",
    NOW(),
    NOW()
),
(
    "swsh4.5-SV106",
    "Gorythmic VMAX",
    "https://assets.tcgdex.net/fr/swsh/swsh4.5/SV106/high.webp",
    "Pokemon",
    "5ban Graphics",
    "Shiny rare VMAX",
    330,
    "Gorythmic-V",
    null,
    "ESCOUADE",
    3,
    2.44,
    20,
    0,
    "swsh4.5",
    NOW(),
    NOW()
),
(
    "swsh4.5-SV107",
    "Dracaufeu VMAX",
    "https://assets.tcgdex.net/fr/swsh/swsh4.5/SV107/high.webp",
    "Pokemon",
    "aky CG Works",
    "Shiny rare VMAX",
    330,
    "Dracaufeu-V",
    null,
    "ESCOUADE",
    3,
    154.11,
    5,
    50,
    "swsh4.5",
    NOW(),
    NOW()
),
(
    "swsh3-1",
    "Papilusion V",
    "https://assets.tcgdex.net/fr/swsh/swsh3/1/high.webp",
    "Pokemon",
    "Saki Hayashiro",
    "Holo Rare V",
    190,
    null,
    null,
    "De base",
    1,
    1.46,
    75,
    0,
    "swsh3",
    NOW(),
    NOW()
);